<a href="https://colab.research.google.com/github/VIGNESHS2005/filpkart-sales-dataset-/blob/main/amazon_fires1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [135]:
import pandas as pd
import numpy as np

In [136]:
df1=pd.read_csv("/content/amazon_fires.csv",encoding="ISO-8859-1")
df1

       ano       mes     estado   numero  encontro
0     1998   Janeiro       Acre  0 Fires  1/1/1998
1     1999   Janeiro       Acre  0 Fires  1/1/1999
2     2000   Janeiro       Acre  0 Fires  1/1/2000
3     2001   Janeiro       Acre  0 Fires  1/1/2001
4     2002   Janeiro       Acre  0 Fires  1/1/2002
...    ...       ...        ...      ...       ...
6449  2012  Dezembro  Tocantins      128  1/1/2012
6450  2013  Dezembro  Tocantins       85  1/1/2013
6451  2014  Dezembro  Tocantins      223  1/1/2014
6452  2015  Dezembro  Tocantins      373  1/1/2015
6453  2016  Dezembro  Tocantins      119  1/1/2016

[6454 rows x 5 columns]

#data cleaning

In [137]:
# step=2 removing the duplicate data value
df1.drop_duplicates(inplace=True)
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6424 entries, 0 to 6453
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ano       6424 non-null   int64
 1   mes       6424 non-null   object
 2   estado    6424 non-null   object
 3   numero    6292 non-null   object
 4   encontro  6424 non-null   object
dtypes: int64(1), object(4)
memory usage: 301.1+ KB

In [138]:
# data cleaning
# rename the columns
d={'ano':'year','mes':'month','estado':'state','numero':'no_of_fores','encontro':'date'}
df1.rename(columns=d,inplace=True)
df1
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6424 entries, 0 to 6453
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   year         6424 non-null   int64
 1   month        6424 non-null   object
 2   state        6424 non-null   object
 3   no_of_fores  6292 non-null   object
 4   date         6424 non-null   object
dtypes: int64(1), object(4)
memory usage: 301.1+ KB

In [139]:
# step=2 removing the duplicate data value
df1.drop_duplicates(inplace=True)
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6424 entries, 0 to 6453
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   year         6424 non-null   int64
 1   month        6424 non-null   object
 2   state        6424 non-null   object
 3   no_of_fores  6292 non-null   object
 4   date         6424 non-null   object
dtypes: int64(1), object(4)
memory usage: 301.1+ KB

In [140]:
df1

      year     month      state no_of_fores      date
0     1998   Janeiro       Acre     0 Fires  1/1/1998
1     1999   Janeiro       Acre     0 Fires  1/1/1999
2     2000   Janeiro       Acre     0 Fires  1/1/2000
3     2001   Janeiro       Acre     0 Fires  1/1/2001
4     2002   Janeiro       Acre     0 Fires  1/1/2002
...    ...       ...        ...         ...       ...
6449  2012  Dezembro  Tocantins         128  1/1/2012
6450  2013  Dezembro  Tocantins          85  1/1/2013
6451  2014  Dezembro  Tocantins         223  1/1/2014
6452  2015  Dezembro  Tocantins         373  1/1/2015
6453  2016  Dezembro  Tocantins         119  1/1/2016

[6424 rows x 5 columns]

In [141]:
#df1.info()
#df1['month'].unique()
#changing the data present in a particular calumn
#syntax:d=['old_value':'new_value']
#d={'janeiro':'january','fevereiro':'febuary','março':'march','abril':'april','maio':'may','junho':'june','julho':'july','agosto':'auguest','setembro':'september','outubro':'octouber','novembro':'noveumber','dezembro':'decmber'}
# 3 changing the data present in a particular column
d={'Janeiro':'january', 'Fevereiro':'febuary', 'Março':'march', 'Abril':'april', 'Maio':'may', 'Junho':'june', 'Julho':'july',
'Agosto':'augest', 'Setembro':'september', 'Outubro':'october', 'Novembro':'november', 'Dezembro':'december'}
df1['month']=df1['month'].map(d)
df1
df1['month'].unique()

array(['january', 'febuary', 'march', 'april', 'may', 'june', 'july',
       'augest', 'september', 'october', 'november', 'december'],
      dtype=object)

In [142]:
df1

      year     month      state no_of_fores      date
0     1998   january       Acre     0 Fires  1/1/1998
1     1999   january       Acre     0 Fires  1/1/1999
2     2000   january       Acre     0 Fires  1/1/2000
3     2001   january       Acre     0 Fires  1/1/2001
4     2002   january       Acre     0 Fires  1/1/2002
...    ...       ...        ...         ...       ...
6449  2012  december  Tocantins         128  1/1/2012
6450  2013  december  Tocantins          85  1/1/2013
6451  2014  december  Tocantins         223  1/1/2014
6452  2015  december  Tocantins         373  1/1/2015
6453  2016  december  Tocantins         119  1/1/2016

[6424 rows x 5 columns]

In [144]:
#4 removing unwanted data from particular col
#df['col_name']=df1['col_name'].str.strip('unwanted')

df1['no_of_fores']=df1['no_of_fores'].str.strip(' Fires')
df1
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6424 entries, 0 to 6453
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   year         6424 non-null   int64
 1   month        6424 non-null   object
 2   state        6424 non-null   object
 3   no_of_fores  6292 non-null   object
 4   date         6424 non-null   object
dtypes: int64(1), object(4)
memory usage: 559.2+ KB

In [145]:
#chaning the object to float value
df1['no_of_fores']=df1['no_of_fores'].astype(float)
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6424 entries, 0 to 6453
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   year         6424 non-null   int64
 1   month        6424 non-null   object
 2   state        6424 non-null   object
 3   no_of_fores  6292 non-null   float64
 4   date         6424 non-null   object
dtypes: float64(1), int64(1), object(3)
memory usage: 559.2+ KB